export const Strings = {
  pt: {
    common: {
      loading: 'A carregar...',
      version: 'Versão {{version}} • Atualizado em {{date}}',
      disclaimer: 'Para referência apenas. Verificar sempre com a farmácia',
      back: 'Voltar',
      highRisk: 'Alto Risco',
      medicationNotFound: 'Medicamento não encontrado',
    },
    navigation: {
      medications: 'Medicamentos',
      favorites: 'Favoritos',
      settings: 'Definições',
    },
    home: {
      searchPlaceholder: 'Pesquisar medicamento...',
      noResults: 'Nenhum medicamento encontrado',
      noData: 'Nenhum medicamento disponível',
    },
    favorites: {
      emptyTitle: 'Sem favoritos',
      emptyMessage: 'Toque no coração ao lado de um medicamento para o adicionar aos favoritos',
    },
    settings: {
      appearance: 'Aparência',
      databaseInfo: 'Informações da Base de Dados',
      about: 'Sobre',
      application: 'Aplicação',
      themes: {
        system: 'Sistema',
        light: 'Claro',
        dark: 'Escuro',
      },
      labels: {
        version: 'Versão',
        lastUpdated: 'Última atualização',
        totalMedications: 'Total de medicamentos',
        appVersion: 'Versão da app',
        mode: 'Modo',
        offlineMode: '100% Offline',
      },
      install: {
        sectionTitle: 'Instalação',
        button: 'Instalar Aplicação',
        iosTitle: 'Instalar no iPhone/iPad',
        iosInstructions: 'Para instalar o Dose Segura no seu iPhone ou iPad:\n\n1. Toque no botão Partilhar\n2. Escolha "Adicionar ao Ecrã Principal"\n3. Toque em "Adicionar"',
        steps: {
          share: 'Toque no botão Partilhar',
          add: 'Escolha "Adicionar ao Ecrã Principal"',
          confirm: 'Toque em "Adicionar"',
        },
        alreadyInstalled: 'A aplicação já está instalada',
        success: 'Abertura do prompt de instalação com sucesso',
        error: 'Não foi possível iniciar a instalação',
        dismiss: 'Entendi',
      },
      aboutText: 'Dose Segura é uma aplicação de referência para auxiliar profissionais de saúde na administração de medicamentos',
      warningText: 'Esta aplicação é apenas para referência. Verifique sempre a informação com fontes oficiais e a farmácia antes de administrar qualquer medicamento',
    },
    medication: {
      disclaimer: '⚠️ Esta informação é apenas para referência. Verifique sempre com a farmácia antes de administrar',
      sections: {
        classification: 'Classificação',
        compatibility: 'Compatibilidade',
        presentationAndStorage: 'Apresentação e Armazenamento',
        preparation: 'Preparação',
        administration: 'Administração',
        stability: 'Estabilidade',
        contraindicationsAndPrecautions: 'Contraindicações e Precauções',
        nursingCare: 'Cuidados de Enfermagem',
      },
    },
  },
};