export const Strings = {
  pt: {
    common: {
      loading: 'A carregar...',
      version: 'Versão {{version}} • Atualizado em {{date}}',
      disclaimer: 'Para referência apenas. Verificar sempre com a farmácia',
      back: 'Voltar',
      cancel: 'Cancelar',
      highRisk: 'Alto Risco',
      medicationNotFound: 'Medicamento não encontrado',
      medicationLoadError: 'Não foi possível carregar os detalhes do medicamento',
    },
    navigation: {
      medications: 'Medicamentos',
      favorites: 'Favoritos',
      calculations: 'Cálculos',
      procedures: 'Procedimentos',
      settings: 'Definições',
      medication: 'Medicamento',
      procedure: 'Procedimento',
      procedureForm: 'Procedimento',
      procedureCatalog: 'Catálogo',
      privacy: 'Privacidade',
      terms: 'Termos',
    },
    notFound: {
      title: 'Página não encontrada',
      message: 'Este caminho não existe no Dose Segura. Volte ao início para continuar.',
      goHome: 'Voltar ao início',
      goBack: 'Voltar atrás',
      requestedPathLabel: 'Caminho pedido',
    },
    accessibility: {
      favoriteMedication: 'Favoritar medicamento',
      favoriteMedicationHint: 'Alterna este medicamento como favorito',
      openMedication: 'Abrir medicamento {{name}}',
      openProcedure: 'Abrir procedimento {{name}}',
      newProcedure: 'Criar novo procedimento',
      addFromCatalog: 'Adicionar do catálogo',
      createProcedure: 'Criar procedimento',
      addCatalogTemplate: 'Adicionar {{name}} do catálogo',
      viewCatalogTemplate: 'Ver detalhes de {{name}}',
      addListItem: 'Adicionar item',
      removeListItem: 'Remover {{name}}',
      openPrivacy: 'Abrir política de privacidade',
      openTerms: 'Abrir termos e aviso médico',
      openContact: 'Contactar por email',
    },
    home: {
      searchPlaceholder: 'Pesquisar medicamento...',
      noResults: 'Nenhum medicamento encontrado',
      noData: 'Nenhum medicamento disponível',
    },
    favorites: {
      emptyTitle: 'Sem favoritos',
      emptyMessage: 'Toque no coração ao lado de um medicamento para o adicionar aos favoritos',
    },
    calculations: {
      intro: 'Ajuda para a regra de três — não é uma calculadora de prescrição',
      next: 'Seguinte',
      optional: 'opcional',
      modes: {
        doseByWeight: 'Dose por peso',
        volume: 'Volume a aspirar',
        mgPerKg: 'mg/kg',
      },
      units: {
        mg: 'mg',
        kg: 'kg',
        mL: 'mL',
        mgPerKg: 'mg/kg',
        mgPerMl: 'mg/mL',
      },
      doseByWeight: {
        doseRefQuestion: 'Qual é a dose de referência?',
        doseRefHint: 'Dose conhecida, em mg (ex.: 100 mg para 70 kg)',
        weightRefQuestion: 'Qual é o peso de referência?',
        weightRefHint: 'Peso para o qual a dose de referência foi calculada, em kg',
        patientWeightQuestion: 'Qual é o peso do doente?',
        patientWeightHint: 'Peso atual do doente, em kg',
        resultLabel: 'Dose do doente',
      },
      volume: {
        prescribedDoseQuestion: 'Qual é a dose prescrita?',
        prescribedDoseHint: 'Dose a administrar, em mg',
        concentrationQuestion: 'Qual é a concentração?',
        concentrationHint: 'Concentração da preparação, em mg/mL',
        resultLabel: 'Volume a aspirar',
      },
      mgPerKg: {
        dosePerKgQuestion: 'Qual é a dose por quilograma?',
        dosePerKgHint: 'Dose em mg por kg de peso',
        patientWeightQuestion: 'Qual é o peso do doente?',
        patientWeightHint: 'Peso atual do doente, em kg',
        concentrationQuestion: 'Qual é a concentração?',
        concentrationHint: 'Se preencher, calculamos também o volume a aspirar, em mg/mL',
        resultLabel: 'Dose',
        volumeLabel: 'Volume a aspirar',
      },
      errors: {
        invalid: 'Introduza um número válido',
        zeroOrNegative: 'Os valores têm de ser maiores do que zero',
      },
      disclaimer:
        'Confirmar sempre com o protocolo/RCM. Esta ajuda não substitui o cálculo independente. Erros de unidade são da responsabilidade de quem administra.',
    },
    settings: {
      appearance: 'Aparência',
      databaseInfo: 'Informações da Base de Dados',
      about: 'Sobre',
      application: 'Aplicação',
      themes: {
        system: 'Sistema',
        light: 'Claro',
        dark: 'Escuro',
      },
      labels: {
        version: 'Versão',
        lastUpdated: 'Última atualização',
        totalMedications: 'Total de medicamentos',
        appVersion: 'Versão da app',
        mode: 'Modo',
        offlineMode: '100% Offline',
      },
      install: {
        sectionTitle: 'Instalação',
        button: 'Instalar Aplicação',
        iosTitle: 'Instalar no iPhone/iPad',
        iosInstructions:
          'Para instalar o Dose Segura no seu iPhone ou iPad:\n\n1. Toque no botão Partilhar\n2. Escolha "Adicionar ao Ecrã Principal"\n3. Toque em "Adicionar"',
        steps: {
          share: 'Toque no botão Partilhar',
          add: 'Escolha "Adicionar ao Ecrã Principal"',
          confirm: 'Toque em "Adicionar"',
        },
        alreadyInstalled: 'A aplicação já está instalada',
        success: 'Abertura do prompt de instalação com sucesso',
        error: 'Não foi possível iniciar a instalação',
        dismiss: 'Entendi',
      },
      aboutText:
        'Dose Segura é uma aplicação de referência para auxiliar profissionais de saúde na administração de medicamentos',
      warningText:
        'Esta aplicação é apenas para referência. Verifique sempre a informação com fontes oficiais e a farmácia antes de administrar qualquer medicamento',
      legal: 'Legal',
      privacy: 'Privacidade',
      terms: 'Termos e aviso',
      contact: 'Contacto',
      contactEmail: 'pmrobalo@gmail.com',
      whatsNew: {
        title: 'Novidades 1.1.0',
        items: [
          'Cálculos pediátricos e regras de três',
          'Procedimentos: criar e editar no menu modular',
          'Catálogo de modelos (CVP, SNG e A-list)',
          'Preview de modelos no catálogo sem adicionar',
          'Modelos B-list: sonda vesical, assistência CVC e arterial',
          'PWA com cache offline e atualização automática',
        ],
      },
    },
    procedures: {
      searchPlaceholder: 'Pesquisar procedimento...',
      emptyTitle: 'Sem procedimentos',
      emptyMessage:
        'Crie um procedimento ou adicione um do catálogo (CVP, SNG). Valide sempre com o protocolo da instituição.',
      noResults: 'Nenhum procedimento encontrado',
      noResultsHint: 'Tente outro termo ou limpe a pesquisa',
      new: 'Novo',
      addMenuTitle: 'Adicionar procedimento',
      createNew: 'Criar procedimento',
      addFromCatalog: 'Adicionar do catálogo',
      catalogTitle: 'Catálogo de procedimentos',
      catalogEmpty: 'Já adicionou todos os procedimentos do catálogo',
      catalogHint:
        'Consulte material, passos e atenção antes de adicionar. Modelos de referência educacional — valide sempre com o protocolo da instituição.',
      viewTemplate: 'Ver',
      addTemplate: 'Adicionar',
      alreadyAdded: 'Já adicionado',
      edit: 'Editar',
      delete: 'Eliminar',
      duplicate: 'Duplicar',
      save: 'Guardar',
      titleLabel: 'Título',
      titlePlaceholder: 'Nome do procedimento',
      materials: 'Material',
      materialItem: 'Material',
      steps: 'Passos',
      stepItem: 'Passo',
      attention: 'O que ter atenção',
      attentionItem: 'Atenção',
      addItem: 'Adicionar',
      itemPlaceholder: 'Descrição',
      builtinBadge: 'Modelo',
      userBadge: 'Meu',
      readOnly: 'Modelo do catálogo — adicione à sua lista para editar',
      disclaimer:
        'Lista de verificação educacional. Não substitui o protocolo da instituição nem a indicação clínica.',
      notFound: 'Procedimento não encontrado',
      deleteTitle: 'Eliminar procedimento',
      deleteMessage:
        'Tem a certeza de que pretende eliminar "{{title}}"? Pode voltar a adicioná-lo a partir do catálogo.',
      cardSummary: '{{materials}} materiais · {{steps}} passos',
      formCreateTitle: 'Novo procedimento',
      formEditTitle: 'Editar procedimento',
      validationTitle: 'Indique um título para o procedimento',
      persistError: 'Não foi possível guardar. As alterações podem perder-se.',
    },
    privacy: {
      title: 'Privacidade',
      lede: 'Como o Dose Segura trata informação na versão 1.',
      offlineTitle: 'Uso offline, sem conta',
      offlineBody:
        'A utilização principal da app não exige criar conta. Os dados de medicamentos e modelos de procedimentos vão incluídos localmente na aplicação para consulta offline.',
      localDataTitle: 'Dados locais',
      localDataBody:
        'Favoritos, tema e procedimentos que criar ficam no armazenamento local do seu dispositivo. Não enviamos estes dados para um servidor nosso.',
      analyticsTitle: 'Sem analytics na v1',
      analyticsBody:
        'Na v1 não há Google Analytics, Plausible, publicidade nem outros rastreadores de produto na aplicação. Não medimos o uso com ferramentas de analytics de terceiros.',
      hostingTitle: 'Alojamento e logs de infra-estrutura',
      hostingBody:
        'Se usar a versão web (por exemplo via GitHub Pages), a infra-estrutura de alojamento pode gerar logs técnicos habituais (como endereço IP e user agent) fora do controlo da app. Isso não é analytics de produto da Dose Segura.',
      contactTitle: 'Contacto sobre privacidade',
      contactBody: 'Questões sobre esta política:',
    },
    terms: {
      title: 'Termos e aviso',
      lede: 'Aviso curto para profissionais que usam o Dose Segura.',
      purposeTitle: 'Ferramenta de referência',
      purposeBody:
        'O Dose Segura é uma ferramenta de referência para apoiar enfermeiros e outros profissionais de saúde. É apenas para referência — não substitui protocolos da instituição, o RCM, a farmácia nem o julgamento clínico.',
      responsibilityTitle: 'Responsabilidade do utilizador',
      responsibilityBody:
        'Confirme sempre a informação com fontes oficiais e a farmácia antes de administrar qualquer medicamento. Erros de unidade, dose ou interpretação são da responsabilidade de quem administra. Esta ajuda não substitui o cálculo independente.',
      calculationsTitle: 'Cálculos e procedimentos',
      calculationsBody:
        'A ajuda de cálculos e as listas de procedimentos são educacionais. Não constituem calculadora de prescrição nem protocolo hospitalar. Valide sempre com o protocolo da instituição.',
      liabilityTitle: 'Limitação de responsabilidade',
      liabilityBody:
        'A aplicação é disponibilizada "como está", sem garantias. Na medida permitida por lei, os mantenedores não são responsáveis por decisões clínicas tomadas com base nesta referência.',
      contactTitle: 'Contacto',
      contactBody: 'Para questões sobre estes termos:',
    },
    medication: {
      disclaimer:
        '⚠️ Esta informação é apenas para referência. Verifique sempre com a farmácia antes de administrar',
      sections: {
        classification: 'Classificação',
        compatibility: 'Compatibilidade',
        presentationAndStorage: 'Apresentação e Armazenamento',
        preparation: 'Preparação',
        administration: 'Administração',
        stability: 'Estabilidade',
        contraindicationsAndPrecautions: 'Contraindicações e Precauções',
        nursingCare: 'Cuidados de Enfermagem',
      },
    },
  },
  en: {
    navigation: {
      privacy: 'Privacy',
      terms: 'Terms',
    },
    notFound: {
      title: 'Page not found',
      message: 'This path does not exist in Dose Segura. Head back home to continue.',
      goHome: 'Back to home',
      goBack: 'Go back',
      requestedPathLabel: 'Requested path',
    },
    accessibility: {
      openPrivacy: 'Open privacy policy',
      openTerms: 'Open terms and medical disclaimer',
      openContact: 'Contact by email',
    },
    settings: {
      legal: 'Legal',
      privacy: 'Privacy',
      terms: 'Terms & disclaimer',
      contact: 'Contact',
      contactEmail: 'pmrobalo@gmail.com',
    },
    privacy: {
      title: 'Privacy',
      lede: 'How Dose Segura handles information in version 1.',
      offlineTitle: 'Offline use, no account',
      offlineBody:
        'Core use of the app does not require creating an account. Medication data and procedure templates ship bundled locally for offline reference.',
      localDataTitle: 'Local data',
      localDataBody:
        'Favorites, theme, and procedures you create stay in local storage on your device. We do not send this data to a first-party backend.',
      analyticsTitle: 'No analytics in v1',
      analyticsBody:
        'In v1 there is no Google Analytics, Plausible, advertising, or other product trackers in the app. We do not measure usage with third-party analytics products.',
      hostingTitle: 'Hosting and infrastructure logs',
      hostingBody:
        "If you use the web build (for example via GitHub Pages), hosting infrastructure may process standard technical logs (such as IP address and user agent) outside the app's control. That is not Dose Segura product analytics.",
      contactTitle: 'Privacy contact',
      contactBody: 'Questions about this policy:',
    },
    terms: {
      title: 'Terms & disclaimer',
      lede: 'A short disclaimer for professionals using Dose Segura.',
      purposeTitle: 'Reference tool',
      purposeBody:
        'Dose Segura is a reference tool to support nurses and other healthcare professionals. It is for reference only — not a substitute for institutional protocols, the SmPC/RCM, pharmacy, or clinical judgment.',
      responsibilityTitle: 'User responsibility',
      responsibilityBody:
        'Always verify information with official sources and pharmacy before administering any medication. Unit, dose, or interpretation errors remain the responsibility of the person administering. This aid does not replace independent calculation.',
      calculationsTitle: 'Calculations and procedures',
      calculationsBody:
        "The calculation aid and procedure checklists are educational. They are not a prescribing calculator or hospital protocol. Always validate against your institution's protocol.",
      liabilityTitle: 'Limitation of liability',
      liabilityBody:
        'The app is provided "as is," without warranties. To the extent permitted by law, the maintainers are not liable for clinical decisions made based on this reference.',
      contactTitle: 'Contact',
      contactBody: 'For questions about these terms:',
    },
  },
};
