/* Generated by scripts/generate-sw-precache.js — do not edit by hand. */
/* eslint-disable no-restricted-globals */
const CACHE_VERSION = "dose-segura-8a2958c9b19d";
const BASE_PATH = "/dose-segura";
const SPA_FALLBACK = "/dose-segura/index.html";
const PRECACHE_URLS = [
  "/dose-segura/",
  "/dose-segura/_expo/.routes.json",
  "/dose-segura/_expo/static/js/web/__common-c9917602e1c31890e88739b5d98f9f3a.js",
  "/dose-segura/_expo/static/js/web/__expo-metro-runtime-0c48b0beee2d3ce6030b475fcc5b1846.js",
  "/dose-segura/_expo/static/js/web/_layout-12b15376b8ea48724bb3f75e7edbbf20.js",
  "/dose-segura/_expo/static/js/web/_layout-3a95f0b8e9730c454fe719abe941536a.js",
  "/dose-segura/_expo/static/js/web/_layout-d8f60fa375287a6e083c970a91deda84.js",
  "/dose-segura/_expo/static/js/web/%2Bnot-found-708478af29246ad567fd5ff95a31db7c.js",
  "/dose-segura/_expo/static/js/web/%5Bid%5D-85336d2b348c784c947c9bf3757637a6.js",
  "/dose-segura/_expo/static/js/web/%5Bid%5D-fec3a5585d2a2e2b541c50e4bd3f2b80.js",
  "/dose-segura/_expo/static/js/web/calculations-2d977108a025c190f17c19d78b50c8a4.js",
  "/dose-segura/_expo/static/js/web/catalog-04b7c9969c44362824d15107adfe00ef.js",
  "/dose-segura/_expo/static/js/web/entry-56fc9e98af8377127a859fa1ce67d160.js",
  "/dose-segura/_expo/static/js/web/favorites-32e4dd70fe07e2cd09455794bff51d9e.js",
  "/dose-segura/_expo/static/js/web/form-4fc0cecf7317ac86b56a46a896fd3689.js",
  "/dose-segura/_expo/static/js/web/index-2d4237c9fcd8a425ef43523ffce3355f.js",
  "/dose-segura/_expo/static/js/web/modal-8a7e7c35b3081979acd7ca106a78102e.js",
  "/dose-segura/_expo/static/js/web/procedures-f28a261d531502d365058519de811934.js",
  "/dose-segura/_expo/static/js/web/settings-c284fcb8acbf2ad990224603fe13036c.js",
  "/dose-segura/_sitemap.html",
  "/dose-segura/(tabs)/calculations.html",
  "/dose-segura/(tabs)/favorites.html",
  "/dose-segura/(tabs)/index.html",
  "/dose-segura/(tabs)/procedures.html",
  "/dose-segura/(tabs)/settings.html",
  "/dose-segura/%2Bnot-found.html",
  "/dose-segura/404.html",
  "/dose-segura/apple-touch-icon.png",
  "/dose-segura/assets/libs/%40expo-google-fonts/quicksand/300Light/Quicksand_300Light.271e0c24a39dadbe933bc774f64f68f5.ttf",
  "/dose-segura/assets/libs/%40expo-google-fonts/quicksand/400Regular/Quicksand_400Regular.5845af22f839a90a9cca3b8ec0e3cff4.ttf",
  "/dose-segura/assets/libs/%40expo-google-fonts/quicksand/500Medium/Quicksand_500Medium.95906e2457ee777801b3ca4b02b4947c.ttf",
  "/dose-segura/assets/libs/%40expo-google-fonts/quicksand/600SemiBold/Quicksand_600SemiBold.dc8fa3ed1fa18875d0aac23ecbf64e02.ttf",
  "/dose-segura/assets/libs/%40expo-google-fonts/quicksand/700Bold/Quicksand_700Bold.8003228962d5cafb549cf4034f9ece07.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/AntDesign.3f78af31cca60105799838a1a7a59fbd.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Entypo.31b5ffea3daddc69dd01a1f3d6cf63c5.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/EvilIcons.140c53a7643ea949007aa9a282153849.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Feather.ca4b48e04dc1ce10bfbddb262c8b835f.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome.b06871f281fee6b241d60582ae9369b9.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Brands.3b89dd103490708d19a95adcae52210e.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Regular.1f77739ca9ff2188b539c36f30ffa2be.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Solid.605ed7926cf39a2ad5ec2d1f9d391d3d.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome6_Brands.56c8d80832e37783f12c05db7c8849e2.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome6_Regular.370dd5af19f8364907b6e2c41f45dbbf.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome6_Solid.adec7d6f310bc577f05e8fe06a5daccf.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Fontisto.b49ae8ab2dbccb02c4d11caaacf09eab.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Foundation.e20945d7c929279ef7a6f1db184a4470.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.b4eb097d35f44ed943676fd56f6bdc51.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.6e435534bd35da5fef04168860a9b8fa.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialIcons.4e85bc9ebe07e0340c9c4fc2f6c38908.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Octicons.871378c6eab492a3e689a9385dc45a12.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/SimpleLineIcons.d2285965fe34b05465047401b8595dd0.ttf",
  "/dose-segura/assets/libs/%40expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Zocial.1681f34aaca71b8dfb70756bca331eb2.ttf",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/back-icon-mask.0a328cd9c1afd0afe8e3b1ec5165b1b4.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/back-icon.35ba0eaec5a4f5ed12ca16fabeae451d.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55%402x.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55%403x.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55%404x.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7%402x.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7%403x.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7%404x.png",
  "/dose-segura/assets/libs/%40react-navigation/elements/lib/module/assets/search-icon.286d67d3f74808a60a78d3ebf1a5fb57.png",
  "/dose-segura/assets/libs/expo-router/assets/arrow_down.017bc6ba3fc25503e5eb5e53826d48a8.png",
  "/dose-segura/assets/libs/expo-router/assets/error.d1ea1496f9057eb392d5bbf3732a61b7.png",
  "/dose-segura/assets/libs/expo-router/assets/file.19eeb73b9593a38f8e9f418337fc7d10.png",
  "/dose-segura/assets/libs/expo-router/assets/forward.d8b800c443b8972542883e0b9de2bdc6.png",
  "/dose-segura/assets/libs/expo-router/assets/pkg.ab19f4cbc543357183a20571f68380a3.png",
  "/dose-segura/assets/libs/expo-router/assets/sitemap.412dd9275b6b48ad28f5e3d81bb1f626.png",
  "/dose-segura/assets/libs/expo-router/assets/unmatched.20e71bdf79e3a97bf55fd9e164041578.png",
  "/dose-segura/calculations.html",
  "/dose-segura/favicon-32.png",
  "/dose-segura/favicon.ico",
  "/dose-segura/favorites.html",
  "/dose-segura/fonts/Quicksand_400Regular.ttf",
  "/dose-segura/fonts/Quicksand_500Medium.ttf",
  "/dose-segura/fonts/Quicksand_600SemiBold.ttf",
  "/dose-segura/fonts/Quicksand_700Bold.ttf",
  "/dose-segura/icon-192.png",
  "/dose-segura/icon-512.png",
  "/dose-segura/icon.png",
  "/dose-segura/index.html",
  "/dose-segura/manifest.json",
  "/dose-segura/medication/%5Bid%5D.html",
  "/dose-segura/meds-full.json",
  "/dose-segura/modal.html",
  "/dose-segura/procedure/%5Bid%5D.html",
  "/dose-segura/procedure/catalog.html",
  "/dose-segura/procedure/form.html",
  "/dose-segura/procedures.html",
  "/dose-segura/robots.txt",
  "/dose-segura/settings.html"
];
const STALE_EXPO_CHUNK_MESSAGE = 'STALE_EXPO_CHUNK';

let staleChunkRecoveryNotified = false;

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_VERSION);
      await Promise.all(
        PRECACHE_URLS.map(async (url) => {
          try {
            await cache.add(url);
          } catch (error) {
            console.warn('[Dose Segura SW] precache failed', url, error);
          }
        }),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== CACHE_VERSION).map((key) => caches.delete(key)));
      await self.clients.claim();
    })(),
  );
});

// Client can nudge activation if a worker is still waiting (belt-and-suspenders
// alongside skipWaiting() during install).
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

function isAppNavigation(request, url) {
  if (request.mode === 'navigate') {
    return true;
  }
  return (
    request.method === 'GET' &&
    request.headers.get('accept') &&
    request.headers.get('accept').includes('text/html') &&
    (url.pathname === BASE_PATH || url.pathname.startsWith(BASE_PATH + '/'))
  );
}

/** Encode each path segment so Expo `[id]` / `+not-found` filenames match GitHub Pages. */
function encodePathnameSegments(pathname) {
  return String(pathname || '')
    .split('/')
    .map((segment) => {
      if (!segment) {
        return segment;
      }
      try {
        return encodeURIComponent(decodeURIComponent(segment));
      } catch {
        return encodeURIComponent(segment);
      }
    })
    .join('/');
}

function toEncodedAssetUrl(url) {
  const encodedPathname = encodePathnameSegments(url.pathname);
  return url.origin + encodedPathname + url.search;
}

function isExpoStaticAsset(url) {
  return (
    url.pathname === BASE_PATH + '/_expo/static' ||
    url.pathname.startsWith(BASE_PATH + '/_expo/static/')
  );
}

function isExpoStaticJs(url) {
  return isExpoStaticAsset(url) && /\.js$/i.test(url.pathname);
}

async function matchCachedAsset(request, url) {
  const direct = await caches.match(request);
  if (direct) {
    return direct;
  }

  const encodedUrl = toEncodedAssetUrl(url);
  if (encodedUrl !== request.url) {
    const encoded = await caches.match(encodedUrl);
    if (encoded) {
      return encoded;
    }
  }

  // Some browsers expose decoded `[id]` in request.url while precache used %5Bid%5D.
  if (url.pathname.includes('%')) {
    try {
      const decodedPath = decodeURIComponent(url.pathname);
      if (decodedPath !== url.pathname) {
        const decodedUrl = url.origin + decodedPath + url.search;
        const decoded = await caches.match(decodedUrl);
        if (decoded) {
          return decoded;
        }
      }
    } catch {
      // ignore malformed percent-encoding
    }
  }

  return undefined;
}

async function notifyStaleExpoChunk(assetUrl) {
  if (staleChunkRecoveryNotified) {
    return;
  }
  staleChunkRecoveryNotified = true;
  const clients = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
  await Promise.all(
    clients.map((client) =>
      client.postMessage({ type: STALE_EXPO_CHUNK_MESSAGE, url: assetUrl }),
    ),
  );
}

async function fetchAssetFromNetwork(request, url) {
  const encodedUrl = toEncodedAssetUrl(url);
  // Prefer percent-encoded segments for Expo static files (GitHub Pages + [id] filenames).
  const candidates = [];
  if (isExpoStaticAsset(url) && encodedUrl !== request.url) {
    candidates.push(encodedUrl);
  }
  candidates.push(request);

  let networkResponse;
  let lastError;
  for (const candidate of candidates) {
    try {
      const response = await fetch(candidate);
      networkResponse = response;
      if (response && response.ok) {
        break;
      }
    } catch (error) {
      lastError = error;
    }
  }

  if (!networkResponse) {
    throw lastError || new Error('[Dose Segura SW] network fetch failed');
  }

  if (networkResponse.ok) {
    const cache = await caches.open(CACHE_VERSION);
    const cacheKey = isExpoStaticAsset(url) ? encodedUrl : request;
    cache.put(cacheKey, networkResponse.clone());
  } else if (networkResponse.status === 404 && isExpoStaticJs(url)) {
    // Online deploy moved hashed chunks; do not keep clients on a broken graph.
    await notifyStaleExpoChunk(url.href);
  }

  return networkResponse;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    return;
  }

  if (!(url.pathname === BASE_PATH || url.pathname.startsWith(BASE_PATH + '/'))) {
    return;
  }

  if (isAppNavigation(request, url)) {
    event.respondWith(
      (async () => {
        try {
          // Network-first for navigations. Never write arbitrary route HTML into
          // SPA_FALLBACK — deep Expo static routes can return different shells
          // than /index.html and would poison offline fallback.
          return await fetch(request);
        } catch (error) {
          // Always serve the precached SPA shell for same-origin app navigations.
          const cached =
            (await caches.match(SPA_FALLBACK)) ||
            (await caches.match(BASE_PATH + '/')) ||
            (await caches.match(BASE_PATH + '/index.html'));
          if (cached) {
            return cached;
          }
          throw error;
        }
      })(),
    );
    return;
  }

  event.respondWith(
    (async () => {
      const cached = await matchCachedAsset(request, url);
      if (cached) {
        return cached;
      }

      try {
        return await fetchAssetFromNetwork(request, url);
      } catch (error) {
        const fallbackCached = await matchCachedAsset(request, url);
        if (fallbackCached) {
          return fallbackCached;
        }
        throw error;
      }
    })(),
  );
});
