import type { Procedure } from '@/types/procedure';

const BUILTIN_UPDATED_AT = '2026-09-11T00:00:00.000Z';

const PROTOCOL_FOOTER =
  'Validar sempre com o protocolo da instituição e o RCM do medicamento. Este conteúdo é de apoio clínico e não substitui normas locais.';

const PROTOCOL_FOOTER_PPCIRA =
  'Validar sempre com o protocolo da instituição / PPCIRA local. Conteúdo de apoio clínico; não substitui normas DGS nem competências OE.';

export const BUILTIN_CVP_ID = 'builtin-cateterismo-venoso-periferico';
export const BUILTIN_SNG_ID = 'builtin-sondagem-nasogastrica';
export const BUILTIN_PREPARACAO_INJECTAVEIS_ID = 'builtin-preparacao-medicamentos-injectaveis';
export const BUILTIN_ADMINISTRACAO_SC_ID = 'builtin-administracao-subcutanea';
export const BUILTIN_ADMINISTRACAO_IM_ID = 'builtin-administracao-intramuscular';
export const BUILTIN_FLUSH_REMOCAO_CVP_ID = 'builtin-flush-remocao-cvp';
export const BUILTIN_MEDICACAO_SNG_ID = 'builtin-medicacao-sonda-nasogastrica';
export const BUILTIN_IV_PUSH_BOLUS_ID = 'builtin-administracao-iv-push-bolus';
export const BUILTIN_SONDAGEM_VESICAL_INSERCAO_ID = 'builtin-sondagem-vesical-insercao';
export const BUILTIN_SONDAGEM_VESICAL_CUIDADOS_REMOCAO_ID =
  'builtin-sondagem-vesical-cuidados-remocao';
export const BUILTIN_ASSISTENCIA_CVC_ID = 'builtin-assistencia-cvc';
export const BUILTIN_ASSISTENCIA_LINHA_ARTERIAL_ID = 'builtin-assistencia-linha-arterial';

export const builtinProcedures: Procedure[] = [
  {
    id: BUILTIN_CVP_ID,
    title: 'Cateterismo venoso periférico',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Compressas',
      'Antisséptico (protocolo local)',
      'Garrote',
      'Cateter de calibre adequado',
      'Penso (preferência transparente se protocolo)',
      'Extensão/tampão/obturador',
      'Contentor de cortantes',
      'Flush segundo protocolo',
    ],
    steps: [
      'Identificar o doente',
      'Explicar o procedimento',
      'Higiene das mãos',
      'Preparar o material; escolher calibre e sítio (preferir distal, evitar flexão; protocolo local)',
      'Aplicar o garrote; avaliar a veia',
      'Antissepsia e tempo de contacto/secagem',
      'Punção asséptica',
      'Confirmar retorno',
      'Avançar o cateter',
      'Soltar o garrote',
      'Mandril para o contentor (nunca reintroduzir)',
      'Ligar obturador/extensão; fixar',
      'Flush segundo protocolo; verificar permeabilidade',
      'Documentar',
    ],
    attention: [
      'Vigiar sinais de flebite, infiltração e extravasamento',
      'Não palpar após antissepsia salvo técnica asséptica mantida',
      'Avaliar diariamente a indicação de manter o CVP; remover se flebite, infiltração, infeção, mau funcionamento ou sem indicação',
      'Respeitar o número máximo de tentativas da instituição',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_SNG_ID,
    title: 'Sondagem nasogástrica',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Compressas',
      'Sonda nasogástrica de calibre adequado',
      'Lubrificante hidrossolúvel',
      'Seringa adaptável',
      'Fita/indicador de pH (se o protocolo usar pH)',
      'Copo com água (se o doente puder colaborar)',
      'Adesivo',
      'Contentor de desperdícios',
      'Material de aspiração disponível',
    ],
    steps: [
      'Identificar o doente',
      'Explicar o procedimento',
      'Higiene das mãos',
      'Preparar o material; escolher calibre conforme objetivo',
      'Posicionar o doente (Semi-Fowler/Fowler se possível)',
      'Avaliar narina mais permeável; medir NEX (nariz–orelha–xifoideu) e marcar',
      'Lubrificar a ponta',
      'Introduzir com técnica asséptica',
      'Pedir para deglutir se o doente estiver consciente',
      'Parar se resistência, tosse, dispneia ou cianose',
      'Verificar o posicionamento segundo o protocolo da instituição (pH do aspirado e/ou RX — nunca auscultação)',
      'Fixar sem compressão da narina',
      'Documentar (medida externa, método de confirmação, pH se aplicável)',
    ],
    attention: [
      'Nunca avançar contra resistência',
      'Sinais de mau posicionamento (tosse, dispneia, cianose) → retirar; não administrar dieta/medicação sem confirmação documentada',
      'Confirmar o posicionamento com o método aceite pela instituição (pH do aspirado / RX quando indicado), nunca por auscultação',
      'Ter presente o risco de broncoaspiração',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_PREPARACAO_INJECTAVEIS_ID,
    title: 'Preparação de medicamentos injectáveis',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Prescrição / registo',
      'Medicamento e diluente indicados',
      'Seringas e agulhas adequadas',
      'Antisséptico / compressas',
      'Rótulos para seringa',
      'Luvas',
      'Contentor de cortantes',
      'EPI se medicamento de alerta máximo / citostático (protocolo)',
    ],
    steps: [
      'Ambiente limpo; higiene das mãos',
      'Verificar prescrição vs medicamento (nome, dose, diluente, via, prazo)',
      'Inspecionar integridade, aspeto, partículas e validade',
      'Desinfetar ampola/tampa do frasco conforme protocolo',
      'Aspirar com agulha/filtro se indicado; reconstituir só com diluente e volume do fabricante',
      'Trocar agulha para administração quando aplicável',
      'Identificar/rotular a seringa de imediato (doente, fármaco, dose, via, hora)',
      'Administrar no prazo do fabricante; não deixar seringas sem identificação',
      'Dupla verificação quando o protocolo exigir (medicamentos de alerta máximo)',
      'Descartar material; documentar a preparação se exigido',
    ],
    attention: [
      'Preferir formas ready-to-administer da farmácia quando disponíveis',
      'Nunca usar seringas de flush pré-cheias para diluir fármacos',
      'Citostáticos / alerta máximo: seguir circuito e EPI institucionais',
      'Quem prepara vs quem administra: seguir o POP local',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_ADMINISTRACAO_SC_ID,
    title: 'Administração subcutânea (SC)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Medicamento preparado e rotulado',
      'Seringa / dispositivo adequado (ex. insulina)',
      'Agulha SC adequada',
      'Antisséptico',
      'Luvas',
      'Compressas',
      'Contentor de cortantes',
    ],
    steps: [
      'Verificar 5/9 certos e alergias',
      'Higiene das mãos; preparar o medicamento; trocar agulha após aspiração se aplicável',
      'Identificar o doente; escolher o local (face externa do braço, antero-lateral da coxa, abdómen ≥5 cm do umbigo, etc.)',
      'Rodar sítios (prevenir lipodistrofia)',
      'Antissepsia; prega cutânea se indicada',
      'Inserir a 45° ou 90° conforme agulha/espessura adiposa (dispositivos pen muitas vezes a 90°)',
      'Aspirar ligeiramente apenas se o protocolo local / RCM o exigir',
      'Injectar lentamente; comprimir sem massajar',
      'Descartar o cortante; registar',
    ],
    attention: [
      'Não massajar o local (aumenta a absorção)',
      'Aspiração SC: ACSS clássico recomenda; muitos protocolos atuais de insulina/vacinas omitem — seguir POP e RCM',
      'Não recapsular agulhas usadas',
      'Observar reacção local/sistémica conforme protocolo',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_ADMINISTRACAO_IM_ID,
    title: 'Administração intramuscular (IM)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Medicamento preparado e rotulado',
      'Seringa e agulha IM adequadas',
      'Antisséptico',
      'Luvas',
      'Compressas',
      'Contentor de cortantes',
    ],
    steps: [
      'Verificar prescrição (doente, fármaco, dose, via IM, hora)',
      'Confirmar alergias / contraindicações; informar o doente',
      'Higiene das mãos; preparar o material',
      'Preparar o medicamento (assepsia; trocar agulha após aspiração de ampola/frasco)',
      'Identificar o doente; posicionar; selecionar local (deltoide / vasto lateral / ventroglúteo ou dorsoglúteo conforme protocolo e formação); rodar sítios',
      'Antissepsia cutânea; deixar secar',
      'Inserir a 90°; aspirar ligeiramente se o protocolo local exigir',
      'Injectar lentamente; retirar no mesmo ângulo; compressão (sem massagem agressiva se contraindicado)',
      'Eliminar a agulha no contentor de cortantes (não recapsular)',
      'Observar reacção; registar local e lote se vacina/injectável rastreável',
    ],
    attention: [
      'Volumes máximos por sítio: confirmar protocolo local',
      'Aspiração IM: prática em evolução — não contradizer o POP local',
      'Preferência ventroglúteo vs dorsoglúteo: seguir formação e POP institucional',
      'Conhecer o procedimento local de anafilaxia',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_FLUSH_REMOCAO_CVP_ID,
    title: 'Flush e remoção de CVP',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Compressas',
      'Antisséptico / descontaminação do hub (protocolo local)',
      'Seringa adequada com NaCl 0,9% (calibre/volume segundo protocolo local)',
      'Penso',
      'Contentor de cortantes / desperdícios',
    ],
    steps: [
      'Flush — higiene das mãos; identificar o doente',
      'Flush — inspecionar o local (dor, eritema, edema, extravasamento)',
      'Flush — descontaminar obturador/hub (protocolo local)',
      'Flush — irrigar com NaCl 0,9% em seringa adequada; técnica push-pause e pressão positiva no final',
      'Flush — antes/depois de medicação ou infusão e entre fármacos incompatíveis',
      'Flush — nunca forçar; se resistência, avaliar e não desobstruir à força; registar',
      'Remoção — confirmar indicação (fim de terapêutica, complicação ou ordem)',
      'Remoção — higiene das mãos; preparar material',
      'Remoção — remover penso e fixações; retirar o cateter paralelamente à pele com movimento contínuo suave',
      'Remoção — compressão até hemostasia; penso; inspecionar integridade da ponta; documentar',
    ],
    attention: [
      'Remover o CVP quando já não houver indicação clínica',
      'Não usar frascos multidose abertos inadequadamente',
      'Nunca forçar contra resistência',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_MEDICACAO_SNG_ID,
    title: 'Medicação por sonda nasogástrica',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Prescrição e formas farmacêuticas adequadas à via sonda',
      'Seringa entérica/adaptável',
      'Água (qualidade conforme protocolo)',
      'Triturador apenas se autorizado',
      'Material para confirmação de posição (pH/RX conforme protocolo)',
      'Luvas',
      'Contentor de desperdícios',
    ],
    steps: [
      'Verificar a prescrição e a adequação da forma farmacêutica à via sonda (consultar farmácia se dúvida)',
      'Confirmar a posição da sonda antes de medicar (pH/RX conforme protocolo — nunca auscultação)',
      'Elevar a cabeceira 30–45° se possível',
      'Interromper a nutrição entérica contínua se aplicável; lavar a sonda',
      'Preferir formas líquidas; diluir viscosos; triturar só o permitido',
      'Um fármaco de cada vez; lavar entre fármacos',
      'Administrar; lavagem final (volumes segundo protocolo e balanço hídrico)',
      'Manter a cabeceira elevada após; reiniciar a nutrição conforme protocolo',
      'Registar (fármacos, volumes de lavagem, confirmação de posição)',
    ],
    attention: [
      'Não triturar / manuseio especial: libertação prolongada, revestimento entérico, sublinguais, alguns grânulos de cápsulas; citostáticos no circuito de segurança',
      'Não misturar fármacos na mesma seringa; não adicionar fármacos ao frasco de dieta',
      'Nunca medicar sem confirmação documentada da posição — nunca por auscultação',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_IV_PUSH_BOLUS_ID,
    title: 'Administração IV push/bolus',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Medicamento preparado e rotulado',
      'Acesso venoso pérvio',
      'NaCl 0,9% para flush',
      'Seringas adequadas',
      'Antisséptico para hub/obturador',
      'Luvas',
      'Contentor de cortantes',
    ],
    steps: [
      'Verificar a prescrição completa (fármaco, dose, diluição, via IV, tempo/velocidade)',
      'Confirmar alergias e compatibilidade com fluidos em curso',
      'Preparar e rotular o medicamento',
      'Higiene das mãos; identificar o doente',
      'Avaliar o acesso: sem flebite/infiltração; permeabilidade',
      'Descontaminar hub/obturador (tempo de fricção do protocolo local)',
      'Flush prévio com NaCl 0,9% segundo protocolo; confirmar patência sem forçar',
      'Administrar lentamente no tempo prescrito/RCM; vigiar o doente',
      'Flush posterior; pressão positiva / clamp conforme dispositivo',
      'Observar reacções; registar (hora, dose, acesso, intercorrências)',
    ],
    attention: [
      'AVISO DE SEGURANÇA: A administração IV em bolus/push é um procedimento de risco elevado (extravasamento, incompatibilidade, velocidade excessiva, erro de via/dose, anafilaxia). Este template é uma lista de verificação de apoio e não substitui o protocolo da instituição, o RCM/folheto do medicamento, a prescrição (incluindo ritmo/tempo de administração) nem a competência do profissional. Em dúvida, não administrar — esclarecer com prescritor/farmácia. Medicamentos de alerta máximo: seguir circuito e dupla verificação locais.',
      'Não administrar irritantes por CVP se o protocolo exigir acesso central',
      'Nunca forçar contra resistência',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_SONDAGEM_VESICAL_INSERCAO_ID,
    title: 'Sondagem vesical (inserção / algaliação)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Kit / algália de menor calibre adequado (tipo e comprimento por sexo/idade/finalidade)',
      'Luvas estéreis e não estéreis',
      'Campo fenestrado',
      'Lubrificante hidrossolúvel estéril (embalagem unitária)',
      'Água destilada/bidestilada e seringa para o balão (volume do fabricante)',
      'Saco de drenagem em circuito fechado (anti-refluxo)',
      'Compressas; resguardo; material de higiene genital',
      'Adesivo / sistema de fixação',
      'Contentor de resíduos',
    ],
    steps: [
      'Identificar o doente; explicar o procedimento; assegurar privacidade',
      'Confirmar indicação apropriada; considerar alternativas (intermitente, cateter externo ♂, etc.); documentar o motivo',
      'Higiene das mãos (DGS 007/2019)',
      'Selecionar o cateter (menor calibre compatível)',
      'Posicionar (♂ dorsal com abdução; ♀ dorsal com flexão e abdução)',
      'Higiene genital com água e sabão; secar; nova higiene das mãos',
      'Técnica asséptica: campo estéril e luvas estéreis; limpeza do meato com solução estéril segundo protocolo local / PPCIRA',
      'Aplicar lubrificante hidrossolúvel estéril',
      'Ligar o cateter ao saco antes ou imediatamente após a inserção → circuito fechado',
      'Inserir sem forçar (♂ cerca de 17–20 cm com gestão do ângulo peniano; ♀ cerca de 5–7,5 cm) até saída de urina',
      'Avançar ligeiramente; encher o balão com água destilada/bidestilada no volume do fabricante (nunca SF 0,9% no balão)',
      'Tracção suave de verificação; fixar (♂ abdómen/coxa superior; ♀ face interna da coxa)',
      'Manter o saco abaixo da bexiga, sem tocar no chão; suporte adequado',
      'Documentar: data/hora, calibre, tipo, volume do balão, indicação, aspeto da urina, reações',
    ],
    attention: [
      'Procedimento invasivo: risco de infeção (IUACV/CAUTI) e trauma uretral; seguir protocolo da instituição e competências do profissional',
      'Nunca forçar contra resistência (trauma / falsa via) — parar, reavaliar e pedir ajuda',
      'Manter apenas enquanto houver indicação; o risco de IUACV acumula diariamente',
      'Sistema fechado: não desligar rotineiramente; prevenção CAUTI (indicação, técnica asséptica, circuito fechado, remoção precoce)',
      'Validar sempre POP/PPCIRA local (antisséptico do meato, kits)',
      PROTOCOL_FOOTER_PPCIRA,
    ],
  },
  {
    id: BUILTIN_SONDAGEM_VESICAL_CUIDADOS_REMOCAO_ID,
    title: 'Sondagem vesical (cuidados e remoção)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Avental (PBCI) quando manusear/esvaziar',
      'Material de higiene do meato (água e sabão)',
      'Recipiente individual para esvaziar o saco',
      'Adesivo / reforço de fixação',
      'Contentor de resíduos',
    ],
    steps: [
      'Manutenção — higiene das mãos antes e depois de manipular o sistema',
      'Manutenção — luvas e avental (PBCI) ao esvaziar ou manusear',
      'Manutenção — higiene diária do meato (água e sabão no banho; sem antissépticos rotineiros desnecessários — DGS 019)',
      'Manutenção — manter circuito fechado; esvaziar o saco a cerca de 2/3; válvula sem tocar no recipiente',
      'Manutenção — saco abaixo da bexiga, fora do chão; fluxo contínuo; fixação sem tracção',
      'Manutenção — amostra de urina só pelo porto próprio (nunca desligar o sistema)',
      'Manutenção — avaliar e documentar diariamente a necessidade de manter; remover se sem indicação (protocolos nurse-driven encorajados)',
      'Remoção — confirmar ordem/protocolo de remoção; explicar; higiene das mãos; luvas',
      'Remoção — esvaziar completamente o balão; retirar suave na expiração/relaxamento; se resistência → parar',
      'Remoção — higiene perineal; estimular micção; vigiar retenção (bladder scan se disponível)',
      'Remoção — documentar hora, volume, aspeto e educação',
    ],
    attention: [
      'Prevenção CAUTI: indicação diária, sistema fechado, remoção precoce',
      'Não irrigar rotineiramente; trocar o sistema se desconexão ou obstrução frequente',
      'Educação do doente/cuidador na alta quando aplicável',
      PROTOCOL_FOOTER_PPCIRA,
    ],
  },
  {
    id: BUILTIN_ASSISTENCIA_CVC_ID,
    title: 'Assistência na colocação de CVC (feixe)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Kit de CVC (mínimo de lúmenes necessário)',
      'Bata e luvas estéreis, touca e máscara para a equipa',
      'Campos de grande dimensão',
      'Clorexidina (CHD) 2% em álcool',
      'SF 0,9%; seringas; lidocaína se prescrita',
      'Penso; sutura/fixação',
      'Contentor de cortantes',
      'Checklist impressa do feixe (DGS/ULSSM)',
    ],
    steps: [
      'Verificar indicação registada e tipo de CVC (mínimo de lúmenes); identificar o doente; explicar riscos/benefícios',
      'Preparar sala/carro; material de barreira máxima; checklist do feixe DGS 022 / ULSSM',
      'Monitorizar sinais vitais de base',
      'Posicionar (ex.: Trendelenburg e rotação da cabeça para jugular; rolo subescapular para subclávia — segundo protocolo)',
      'Higiene das mãos; apoiar preparação tipo pré-cirúrgica do operador e ajudantes',
      'Garantir barreiras de proteção máxima (bata + luvas estéreis, touca, máscara; campos cobrindo a maior parte do corpo) em todos os intervenientes no raio do procedimento',
      'Apoiar antissepsia da pele com CHD 2% alcoólica: friccionar e deixar secar (tempos segundo fabricante e POP; não tocar após)',
      'Durante a inserção: manter assépsia; passar material estéril; nunca reintroduzir porção exteriorizada',
      'Após: conectar sistemas estéreis; penso asséptico datado; fixação',
      'Assegurar confirmação de posição por RX quando aplicável; vigiar pneumotórax, hemorragia e arritmia',
      'Documentar: local, lúmenes, lote, operadores, cumprimento do feixe (sim/não por item) e exceções fundamentadas',
    ],
    attention: [
      'AVISO DE SEGURANÇA: Assistência e colaboração com o médico / profissional competente na colocação — este template NÃO implica inserção independente de CVC não-tunelado pelo enfermeiro de cuidados gerais. PICC exige formação acreditada e protocolo institucional (OE Parecer 29/2020) e não equivale a CVC geral.',
      'Feixe DGS 022 (tudo ou nada): higiene das mãos; barreiras máximas; CHD 2% alcoólica com secagem; evitar acesso femoral (preferir subclávia/jugular); competência/treino e mínimo de lúmenes',
      'Riscos: CLABSI, pneumotórax, hemorragia, arritmia, embolia gasosa, malposição',
      'CVC de emergência sem assépsia adequada → substituir ≤48 h (ULSSM/ACSS)',
      'Manutenção (penso/hubs/remoção diária) é enfermagem com treino — ver POP/PPCIRA; não é o corpo principal deste template',
      PROTOCOL_FOOTER_PPCIRA,
    ],
  },
  {
    id: BUILTIN_ASSISTENCIA_LINHA_ARTERIAL_ID,
    title: 'Assistência na colocação de linha arterial',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Cateter arterial adequado e kit',
      'Luvas estéreis, bata/avental, touca, máscara; campo fenestrado',
      'CHD 2% em álcool',
      'Kit de transdutor descartável; cabo PAI; bolsa pressurizadora',
      'SF 0,9% (heparina só se o protocolo local o exigir)',
      'Penso estéril',
      'Contentor de cortantes',
    ],
    steps: [
      'Confirmar indicação e identidade; explicar; monitorização básica',
      'Teste de circulação colateral se radial (Allen/Barbeau — segundo protocolo local)',
      'Preparar material e montar circuito PAI: SF 0,9%, transdutor de uso único, pressurizador cerca de 300 mmHg, purge de ar',
      'Posicionar o membro; higiene das mãos; apoiar barreiras',
      'Barreiras mínimas (ULSSM): touca, máscara, bata/avental, luvas estéreis, campo fenestrado; se femoral/axilar → barreiras de proteção máxima (como CVC)',
      'Apoiar antissepsia com CHD 2% alcoólica (fricção + secar) pelo operador',
      'Após inserção pelo profissional competente: conectar o sistema sem ar; verificar refluxo arterial; flush; fixar; penso estéril',
      'Nivelar e zerar o transdutor (eixo flebostático / 4.º EIC linha média axilar — POP)',
      'Vigiar curva, perfusão distal, sangramento e hematoma; alarmes',
      'Documentar local, lado, data/hora, operador, tipo de cateter e testes',
    ],
    attention: [
      'AVISO DE SEGURANÇA: Assistência / colaboração com o médico / profissional competente — NÃO apresentar o enfermeiro generalista como operador autónomo da punção arterial, salvo protocolo institucional explícito e competências reconhecidas',
      'Riscos: hemorragia, isquemia distal, trombose, infeção, embolia aérea no sistema',
      'Nunca injectar medicamentos pela linha arterial salvo protocolo explícito de emergência',
      'Preferir radial/braquial/pediosa vs femoral/axilar (ULSSM); remover logo que desnecessário; não troca rotineira sem indicação',
      'Transdutores/componentes: intervalo de 96 h (ULSSM) salvo POP diferente',
      PROTOCOL_FOOTER_PPCIRA,
    ],
  },
];
