import type { Procedure } from '@/types/procedure';

const BUILTIN_UPDATED_AT = '2026-09-11T00:00:00.000Z';

const PROTOCOL_FOOTER =
  'Validar sempre com o protocolo da instituição e o RCM do medicamento. Este conteúdo é de apoio clínico e não substitui normas locais.';

export const BUILTIN_CVP_ID = 'builtin-cateterismo-venoso-periferico';
export const BUILTIN_SNG_ID = 'builtin-sondagem-nasogastrica';
export const BUILTIN_PREPARACAO_INJECTAVEIS_ID = 'builtin-preparacao-medicamentos-injectaveis';
export const BUILTIN_ADMINISTRACAO_SC_ID = 'builtin-administracao-subcutanea';
export const BUILTIN_ADMINISTRACAO_IM_ID = 'builtin-administracao-intramuscular';
export const BUILTIN_FLUSH_REMOCAO_CVP_ID = 'builtin-flush-remocao-cvp';
export const BUILTIN_MEDICACAO_SNG_ID = 'builtin-medicacao-sonda-nasogastrica';
export const BUILTIN_IV_PUSH_BOLUS_ID = 'builtin-administracao-iv-push-bolus';

export const builtinProcedures: Procedure[] = [
  {
    id: BUILTIN_CVP_ID,
    title: 'Cateterismo venoso periférico',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Compressas',
      'Antisséptico (protocolo local)',
      'Garrote',
      'Cateter de calibre adequado',
      'Penso (preferência transparente se protocolo)',
      'Extensão/tampão/obturador',
      'Contentor de cortantes',
      'Flush segundo protocolo',
    ],
    steps: [
      'Identificar o doente',
      'Explicar o procedimento',
      'Higiene das mãos',
      'Preparar o material; escolher calibre e sítio (preferir distal, evitar flexão; protocolo local)',
      'Aplicar o garrote; avaliar a veia',
      'Antissepsia e tempo de contacto/secagem',
      'Punção asséptica',
      'Confirmar retorno',
      'Avançar o cateter',
      'Soltar o garrote',
      'Mandril para o contentor (nunca reintroduzir)',
      'Ligar obturador/extensão; fixar',
      'Flush segundo protocolo; verificar permeabilidade',
      'Documentar',
    ],
    attention: [
      'Vigiar sinais de flebite, infiltração e extravasamento',
      'Não palpar após antissepsia salvo técnica asséptica mantida',
      'Avaliar diariamente a indicação de manter o CVP; remover se flebite, infiltração, infeção, mau funcionamento ou sem indicação',
      'Respeitar o número máximo de tentativas da instituição',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_SNG_ID,
    title: 'Sondagem nasogástrica',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Compressas',
      'Sonda nasogástrica de calibre adequado',
      'Lubrificante hidrossolúvel',
      'Seringa adaptável',
      'Fita/indicador de pH (se o protocolo usar pH)',
      'Copo com água (se o doente puder colaborar)',
      'Adesivo',
      'Contentor de desperdícios',
      'Material de aspiração disponível',
    ],
    steps: [
      'Identificar o doente',
      'Explicar o procedimento',
      'Higiene das mãos',
      'Preparar o material; escolher calibre conforme objetivo',
      'Posicionar o doente (Semi-Fowler/Fowler se possível)',
      'Avaliar narina mais permeável; medir NEX (nariz–orelha–xifoideu) e marcar',
      'Lubrificar a ponta',
      'Introduzir com técnica asséptica',
      'Pedir para deglutir se o doente estiver consciente',
      'Parar se resistência, tosse, dispneia ou cianose',
      'Verificar o posicionamento segundo o protocolo da instituição (pH do aspirado e/ou RX — nunca auscultação)',
      'Fixar sem compressão da narina',
      'Documentar (medida externa, método de confirmação, pH se aplicável)',
    ],
    attention: [
      'Nunca avançar contra resistência',
      'Sinais de mau posicionamento (tosse, dispneia, cianose) → retirar; não administrar dieta/medicação sem confirmação documentada',
      'Confirmar o posicionamento com o método aceite pela instituição (pH do aspirado / RX quando indicado), nunca por auscultação',
      'Ter presente o risco de broncoaspiração',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_PREPARACAO_INJECTAVEIS_ID,
    title: 'Preparação de medicamentos injectáveis',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Prescrição / registo',
      'Medicamento e diluente indicados',
      'Seringas e agulhas adequadas',
      'Antisséptico / compressas',
      'Rótulos para seringa',
      'Luvas',
      'Contentor de cortantes',
      'EPI se medicamento de alerta máximo / citostático (protocolo)',
    ],
    steps: [
      'Ambiente limpo; higiene das mãos',
      'Verificar prescrição vs medicamento (nome, dose, diluente, via, prazo)',
      'Inspecionar integridade, aspeto, partículas e validade',
      'Desinfetar ampola/tampa do frasco conforme protocolo',
      'Aspirar com agulha/filtro se indicado; reconstituir só com diluente e volume do fabricante',
      'Trocar agulha para administração quando aplicável',
      'Identificar/rotular a seringa de imediato (doente, fármaco, dose, via, hora)',
      'Administrar no prazo do fabricante; não deixar seringas sem identificação',
      'Dupla verificação quando o protocolo exigir (medicamentos de alerta máximo)',
      'Descartar material; documentar a preparação se exigido',
    ],
    attention: [
      'Preferir formas ready-to-administer da farmácia quando disponíveis',
      'Nunca usar seringas de flush pré-cheias para diluir fármacos',
      'Citostáticos / alerta máximo: seguir circuito e EPI institucionais',
      'Quem prepara vs quem administra: seguir o POP local',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_ADMINISTRACAO_SC_ID,
    title: 'Administração subcutânea (SC)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Medicamento preparado e rotulado',
      'Seringa / dispositivo adequado (ex. insulina)',
      'Agulha SC adequada',
      'Antisséptico',
      'Luvas',
      'Compressas',
      'Contentor de cortantes',
    ],
    steps: [
      'Verificar 5/9 certos e alergias',
      'Higiene das mãos; preparar o medicamento; trocar agulha após aspiração se aplicável',
      'Identificar o doente; escolher o local (face externa do braço, antero-lateral da coxa, abdómen ≥5 cm do umbigo, etc.)',
      'Rodar sítios (prevenir lipodistrofia)',
      'Antissepsia; prega cutânea se indicada',
      'Inserir a 45° ou 90° conforme agulha/espessura adiposa (dispositivos pen muitas vezes a 90°)',
      'Aspirar ligeiramente apenas se o protocolo local / RCM o exigir',
      'Injectar lentamente; comprimir sem massajar',
      'Descartar o cortante; registar',
    ],
    attention: [
      'Não massajar o local (aumenta a absorção)',
      'Aspiração SC: ACSS clássico recomenda; muitos protocolos atuais de insulina/vacinas omitem — seguir POP e RCM',
      'Não recapsular agulhas usadas',
      'Observar reacção local/sistémica conforme protocolo',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_ADMINISTRACAO_IM_ID,
    title: 'Administração intramuscular (IM)',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Medicamento preparado e rotulado',
      'Seringa e agulha IM adequadas',
      'Antisséptico',
      'Luvas',
      'Compressas',
      'Contentor de cortantes',
    ],
    steps: [
      'Verificar prescrição (doente, fármaco, dose, via IM, hora)',
      'Confirmar alergias / contraindicações; informar o doente',
      'Higiene das mãos; preparar o material',
      'Preparar o medicamento (assepsia; trocar agulha após aspiração de ampola/frasco)',
      'Identificar o doente; posicionar; selecionar local (deltoide / vasto lateral / ventroglúteo ou dorsoglúteo conforme protocolo e formação); rodar sítios',
      'Antissepsia cutânea; deixar secar',
      'Inserir a 90°; aspirar ligeiramente se o protocolo local exigir',
      'Injectar lentamente; retirar no mesmo ângulo; compressão (sem massagem agressiva se contraindicado)',
      'Eliminar a agulha no contentor de cortantes (não recapsular)',
      'Observar reacção; registar local e lote se vacina/injectável rastreável',
    ],
    attention: [
      'Volumes máximos por sítio: confirmar protocolo local',
      'Aspiração IM: prática em evolução — não contradizer o POP local',
      'Preferência ventroglúteo vs dorsoglúteo: seguir formação e POP institucional',
      'Conhecer o procedimento local de anafilaxia',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_FLUSH_REMOCAO_CVP_ID,
    title: 'Flush e remoção de CVP',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Luvas',
      'Compressas',
      'Antisséptico / descontaminação do hub (protocolo local)',
      'Seringa adequada com NaCl 0,9% (calibre/volume segundo protocolo local)',
      'Penso',
      'Contentor de cortantes / desperdícios',
    ],
    steps: [
      'Flush — higiene das mãos; identificar o doente',
      'Flush — inspecionar o local (dor, eritema, edema, extravasamento)',
      'Flush — descontaminar obturador/hub (protocolo local)',
      'Flush — irrigar com NaCl 0,9% em seringa adequada; técnica push-pause e pressão positiva no final',
      'Flush — antes/depois de medicação ou infusão e entre fármacos incompatíveis',
      'Flush — nunca forçar; se resistência, avaliar e não desobstruir à força; registar',
      'Remoção — confirmar indicação (fim de terapêutica, complicação ou ordem)',
      'Remoção — higiene das mãos; preparar material',
      'Remoção — remover penso e fixações; retirar o cateter paralelamente à pele com movimento contínuo suave',
      'Remoção — compressão até hemostasia; penso; inspecionar integridade da ponta; documentar',
    ],
    attention: [
      'Remover o CVP quando já não houver indicação clínica',
      'Não usar frascos multidose abertos inadequadamente',
      'Nunca forçar contra resistência',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_MEDICACAO_SNG_ID,
    title: 'Medicação por sonda nasogástrica',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Prescrição e formas farmacêuticas adequadas à via sonda',
      'Seringa entérica/adaptável',
      'Água (qualidade conforme protocolo)',
      'Triturador apenas se autorizado',
      'Material para confirmação de posição (pH/RX conforme protocolo)',
      'Luvas',
      'Contentor de desperdícios',
    ],
    steps: [
      'Verificar a prescrição e a adequação da forma farmacêutica à via sonda (consultar farmácia se dúvida)',
      'Confirmar a posição da sonda antes de medicar (pH/RX conforme protocolo — nunca auscultação)',
      'Elevar a cabeceira 30–45° se possível',
      'Interromper a nutrição entérica contínua se aplicável; lavar a sonda',
      'Preferir formas líquidas; diluir viscosos; triturar só o permitido',
      'Um fármaco de cada vez; lavar entre fármacos',
      'Administrar; lavagem final (volumes segundo protocolo e balanço hídrico)',
      'Manter a cabeceira elevada após; reiniciar a nutrição conforme protocolo',
      'Registar (fármacos, volumes de lavagem, confirmação de posição)',
    ],
    attention: [
      'Não triturar / manuseio especial: libertação prolongada, revestimento entérico, sublinguais, alguns grânulos de cápsulas; citostáticos no circuito de segurança',
      'Não misturar fármacos na mesma seringa; não adicionar fármacos ao frasco de dieta',
      'Nunca medicar sem confirmação documentada da posição — nunca por auscultação',
      PROTOCOL_FOOTER,
    ],
  },
  {
    id: BUILTIN_IV_PUSH_BOLUS_ID,
    title: 'Administração IV push/bolus',
    source: 'builtin',
    updatedAt: BUILTIN_UPDATED_AT,
    materials: [
      'Medicamento preparado e rotulado',
      'Acesso venoso pérvio',
      'NaCl 0,9% para flush',
      'Seringas adequadas',
      'Antisséptico para hub/obturador',
      'Luvas',
      'Contentor de cortantes',
    ],
    steps: [
      'Verificar a prescrição completa (fármaco, dose, diluição, via IV, tempo/velocidade)',
      'Confirmar alergias e compatibilidade com fluidos em curso',
      'Preparar e rotular o medicamento',
      'Higiene das mãos; identificar o doente',
      'Avaliar o acesso: sem flebite/infiltração; permeabilidade',
      'Descontaminar hub/obturador (tempo de fricção do protocolo local)',
      'Flush prévio com NaCl 0,9% segundo protocolo; confirmar patência sem forçar',
      'Administrar lentamente no tempo prescrito/RCM; vigiar o doente',
      'Flush posterior; pressão positiva / clamp conforme dispositivo',
      'Observar reacções; registar (hora, dose, acesso, intercorrências)',
    ],
    attention: [
      'AVISO DE SEGURANÇA: A administração IV em bolus/push é um procedimento de risco elevado (extravasamento, incompatibilidade, velocidade excessiva, erro de via/dose, anafilaxia). Este template é uma lista de verificação de apoio e não substitui o protocolo da instituição, o RCM/folheto do medicamento, a prescrição (incluindo ritmo/tempo de administração) nem a competência do profissional. Em dúvida, não administrar — esclarecer com prescritor/farmácia. Medicamentos de alerta máximo: seguir circuito e dupla verificação locais.',
      'Não administrar irritantes por CVP se o protocolo exigir acesso central',
      'Nunca forçar contra resistência',
      PROTOCOL_FOOTER,
    ],
  },
];
